import localFont from "next/font/local";
import "./globals.css";

const AtHauss = localFont({
  src: "./fonts/HostGrotesk-VariableFont_wght.ttf",
  variable: "--font-at-hauss",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${AtHauss.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
